cc_library(
    name = "gamepad",
    srcs = glob(["*.cpp", "*.h"]),
    deps = [
        "@common//frame:frame",
    ],
    copts = ["-Iexternal/common/frame"],
    visibility = ["//visibility:public"],
)
